### ISSUE TITLE
Creación de un endpoint que obtengamos una pregunta tipo test de forma aleatória

### ISSUE THREAD

**Issue by omiras** [IronHack-2024/CodeQuestAPI#1]
## Objetivo

Crear un endpoint `/api/v1/questions/random`

## Ánalisis

1. Inicializar un proyecto con NPM
2. Subir el proyecto a GitHub
3. Instlar las dependencias necesarias
4. Necesitamos crear un nuevo endpoint 
5. Necesitamos acceso a una base de datos de MongoDB (MongoDB Atlas)
  1. Necesitamos crear una cuenta en MongoDB Atlas y configurarla correctamente
6. Crear una cuenta de correo para los servicios de MongoDB Atlas para Render.com. Crear una cuenta de GMAIL u otros servicio correo y compartir las claves de acceso en el grupo de Slack #proyecto-final
7. Crear un modelo de Mongoose  para almacenar las preguntas tipo test
    - ¿Cómo almacenar las 4 respuestas posible? ¿Array de strings?
    - ¿Cómo marcamos la respuesta correcta?
9. Insertar al menos 10 pregunas tipo test   
10. Variables de entorno. Parece ser que ahora NodeJS no requiere de instalar el módulo _dotenv_. ¡Podemos probar si queréis! - [enlace](https://www.linkedin.com/posts/midudev_ya-no-necesitas-instalar-dotenv-en-node-activity-7253805585639374848-8FCn?utm_source=share&utm_medium=member_desktop)

## Cómo probar la issue

Debemos explicar a nuestros compañeros como pueden probar que la tarea funciona. ¿Que pasos deben seguir? Recordad que los pantallazos con la salida por ejemplo de Thnder Client pueden ser muy útiles para clarificar que es lo que tiene que pasar - [screenshot](https://oscarm.tinytake.com/media/16b1240?filename=1726757648300_TinyTake19-09-2024-04-53-42_638623544484427270.png&sub_type=thumbnail_preview&type=attachment&width=1200&height=457)

Adicionalmente, podéis crear un par de tests para probar el endpoint tal y como hicimos en clase - [enlace](https://github.com/omiras/emotional-shelf/blob/solution/tests/api.test.js)

**Comment by omiras** [comment]
¿Que estructura pensáis que debería tener una pregunta tipo test? Podéis dar un ejemplo usando un objeto de JavaScript o directamente un modelo de Mongoose.

**Comment by crimanlor** [comment]
Una posible opción, sería que el esquema "Question" tuviera los siguientes campos:
- **Description**: corresponde al texto de la pregunta.
- **Options**: a cada una de las posibles respuestas.
- **Category**: tipología de la pregunta.
- **Level**: nivel de dificultad de cada pregunta.
- **CreatedAt**: para llevar un registro de qué preguntas están más actualizadas.

 ```
 const questionSchema = new mongoose.Schema({
  description: {
    type: String,
    required: true,
  },
  options: [
    {
      label: {
        type: String,
        enum: ['a', 'b', 'c', 'd'],
        required: true,
      },
      text: {
        type: String,
        required: true,
      },
      isCorrect: {
        type: Boolean, 
        default: false,
      }
    }
  ],
  category: {
    type: String,
    required: true,
  },
  level: {
    type: String,
    enum: ['easy', 'medium', 'hard'],
    default: 'medium',
  },
  createdAt: {
    type: Date,
    default: Date.now,
  },
});
   ```

**Comment by kevmhughes** [comment]
Quizás podríamos usar la opción nativa de Mongoose para gestionar automáticamente la creación y actualización de los documentos: { timestamps: true }.

Al habilitar { timestamps: true } en la configuración del esquema, Mongoose automáticamente añade y gestiona dos campos:

createdAt: que almacena la fecha y hora en que se creó el documento.
updatedAt: que se actualiza automáticamente cada vez que se modifica el documento.

```
const questionSchema = new mongoose.Schema({
  description: {
    type: String,
    required: true,
  },
  options: [
    {
      label: {
        type: String,
        enum: ['a', 'b', 'c', 'd'],
        required: true,
      },
      text: {
        type: String,
        required: true,
      },
      isCorrect: {
        type: Boolean,
        default: false,
      },
    },
  ],
  category: {
    type: String,
    required: true,
  },
  level: {
    type: String,
    enum: ['easy', 'medium', 'hard'],
    default: 'medium',
  },
}, { timestamps: true });
```

**Comment by kevmhughes** [comment]
Sugiero otros campos que podrían añadirse al esquema que ha sugerido Lorena.

```
const questionSchema = new mongoose.Schema({
  description: {
    type: String,
    required: true,  // Main question text
  },
  codeSnippet: {
    type: String,    // Optional code snippet relevant to the question
    required: false,
  },
  options: [
    {
      label: {
        type: String,
        enum: ['a', 'b', 'c', 'd'],  // Option labels, constrained to four choices
        required: true,
      },
      text: {
        type: String,  // The actual option text
        required: true,
      },
      isCorrect: {
        type: Boolean,  // Indicates if the option is correct
        default: false,
      }
    }
  ],
  explanation: {
    correct: {
      type: String,  // Explanation for why the correct option is right
      required: false,
    },
    incorrect: {
      type: String,  // General explanation for why other options are wrong
      required: false,
    }
  },
  tags: {
    type: [String],  // List of relevant programming topics or concepts (e.g., 'JavaScript', 'OOP', 'Recursion')
    required: false,
  },
  language: {
    type: String,  // The programming language related to the question (e.g., 'JavaScript', 'Python')
    required: true,
  },
  level: {
    type: String,
    enum: ['easy', 'medium', 'hard'],  // Difficulty level of the question
    default: 'medium',
  },
}, { timestamps: true });  // Automatically add createdAt and updatedAt

```

**Comment by SharmarAndrey** [comment]
> ¿Que estructura pensáis que debería tener una pregunta tipo test? Podéis dar un ejemplo usando un objeto de JavaScript o directamente un modelo de Mongoose.

// Ejemplo de objeto JavaScript
const testQuestion = {
  questionText: '¿Question ?', // Texto de la pregunta
  options: [
    { text: 'a', isCorrect: false }, // Opción de respuesta: texto e indicación de si es la respuesta correcta
    { text: 'b', isCorrect: true },
    { text: 'c', isCorrect: false },
    { text: 'd', isCorrect: false }
  ],
  difficulty: 'fácil', // Nivel de dificultad de la pregunta 
  category: 'Java Script', // Categoría de la pregunta 
  explanation: 'La suma de 2 + 2 es igual a 4.' // Explicación de la respuesta correcta
};

// Ejemplo de modelo Mongoose
const mongoose = require('mongoose');

const QuestionSchema = new mongoose.Schema({
  questionText: {
    type: String,
    required: true // Texto de la pregunta
  },
  options: [
    {
      text: {
        type: String,
        required: true // Texto de la opción de respuesta 
      },
      isCorrect: {
        type: Boolean,
        required: true // Indicación de si esta opción de respuesta es correcta 
      }
    }
  ],
  difficulty: {
    type: String,
    enum: ['fácil', 'medio', 'difícil'], // Nivel de dificultad 
    required: true // Campo obligatorio
  },
  category: {
    type: String,
    required: true // Categoría de la pregunta (por ejemplo, Java Script)
  },
  explanation: {
    type: String // Explicación de la respuesta correcta 
  }
});

const Question = mongoose.model('Question', QuestionSchema);

module.exports = Question;

**Comment by MariaChmielinska** [comment]
Yo añadiría también la tecnología y el idioma. No se si Lorena con category quiere decir Dev Category como Front End, BackEnd?
```
  tech: {
    type: String,
    enum: ['python', 'css', 'java script', etc.],
    required: true,
  },
  language: {
    type: String,
    enum: ['english', 'german', 'spanish', etc.],
    required: true,
  },
```

**Comment by ekbalam11** [comment]
## Mi respuesta

```
const pregunta = {
    id: {
        type: Number
    },
    enunciado: {
        type: String
    }, //la pregunta como tal
    tema: {
        type: String,
        enum: ['Aquí van los tags']
    }, //una especie de tag
    respuestas: {
        opcion1,
        opcion2,
        opcion3,
        opcionEtc
    },
    explicación: {
        type: String
    },
    lenguaje: {
        type: String,
        enum: ['python', 'etc'] //lista de lenguajes posibles
    },
    source: {
        type: String,
        //Fuente de información de donde se obtuvo la respuesta
 }
```

**Comment by SharmarAndrey** [comment]
> ¿Que estructura pensáis que debería tener una pregunta tipo test? Podéis dar un ejemplo usando un objeto de JavaScript o directamente un modelo de Mongoose.
```
// Ejemplo de objeto JavaScript
const testQuestion = {
  questionText: '¿Question ?', // Texto de la pregunta
  options: [
    { text: 'a', isCorrect: false }, // Opción de respuesta: texto e indicación de si es la respuesta correcta
    { text: 'b', isCorrect: true },
    { text: 'c', isCorrect: false },
    { text: 'd', isCorrect: false }
  ],
  difficulty: 'fácil', // Nivel de dificultad de la pregunta 
  category: 'Java Script', // Categoría de la pregunta 
  explanation: 'explicacion de la respuesta' // Explicación de la respuesta correcta
};

// Función para mezclar las opciones de respuesta
function shuffleOptions(question) {
  question.options = question.options.sort(() => Math.random() - 0.5);
}


shuffleOptions(testQuestion);
console.log(testQuestion);

// Ejemplo de modelo Mongoose
const mongoose = require('mongoose');

const QuestionSchema = new mongoose.Schema({
  questionText: {
    type: String,
    required: true // Texto de la pregunta
  },
  options: [
    {
      text: {
        type: String,
        required: true // Texto de la opción de respuesta 
      },
      isCorrect: {
        type: Boolean,
        required: true // Indicación de si esta opción de respuesta es correcta 
      }
    }
  ],
  difficulty: {
    type: String,
    enum: ['fácil', 'medio', 'difícil'], // Nivel de dificultad 
    required: true // Campo obligatorio
  },
  category: {
    type: String,
    required: true // Categoría de la pregunta (por ejemplo, Java Script)
  },
  explanation: {
    type: String // Explicación de la respuesta correcta 
  }
});

const Question = mongoose.model('Question', QuestionSchema);

module.exports = Question;
```

**Comment by omiras** [comment]
Buen trabajo a todos los qe habéis pensado el mejor modelo de datos.
Recordad al implementar vuestro modelo de Mongoose el lema : 

![image](https://github.com/user-attachments/assets/16f5fe30-af98-4ce4-acb9-6882dd97c699)

“Always implement things when you actually need them, never when you just foresee that you need them.”

**Comment by MariaChmielinska** [comment]
email address: codequestapi@gmail.com
pw: IronHack2024

**Comment by omiras** [comment]
> email address: [codequestapi@gmail.com](mailto:codequestapi@gmail.com) pw: IronHack2024

Esto es mejor que no esté aquí, solo en Slack. Porque el proyecto es **publico** y cualquiera puede ver las credenciales ;)

**Comment by omiras** [comment]
> > ¿Que estructura pensáis que debería tener una pregunta tipo test? Podéis dar un ejemplo usando un objeto de JavaScript o directamente un modelo de Mongoose.
> 
> ```
> // Ejemplo de objeto JavaScript
> const testQuestion = {
>   questionText: '¿Question ?', // Texto de la pregunta
>   options: [
>     { text: 'a', isCorrect: false }, // Opción de respuesta: texto e indicación de si es la respuesta correcta
>     { text: 'b', isCorrect: true },
>     { text: 'c', isCorrect: false },
>     { text: 'd', isCorrect: false }
>   ],
>   difficulty: 'fácil', // Nivel de dificultad de la pregunta 
>   category: 'Java Script', // Categoría de la pregunta 
>   explanation: 'explicacion de la respuesta' // Explicación de la respuesta correcta
> };
> 
> // Función para mezclar las opciones de respuesta
> function shuffleOptions(question) {
>   question.options = question.options.sort(() => Math.random() - 0.5);
> }
> 
> 
> shuffleOptions(testQuestion);
> console.log(testQuestion);
> 
> // Ejemplo de modelo Mongoose
> const mongoose = require('mongoose');
> 
> const QuestionSchema = new mongoose.Schema({
>   questionText: {
>     type: String,
>     required: true // Texto de la pregunta
>   },
>   options: [
>     {
>       text: {
>         type: String,
>         required: true // Texto de la opción de respuesta 
>       },
>       isCorrect: {
>         type: Boolean,
>         required: true // Indicación de si esta opción de respuesta es correcta 
>       }
>     }
>   ],
>   difficulty: {
>     type: String,
>     enum: ['fácil', 'medio', 'difícil'], // Nivel de dificultad 
>     required: true // Campo obligatorio
>   },
>   category: {
>     type: String,
>     required: true // Categoría de la pregunta (por ejemplo, Java Script)
>   },
>   explanation: {
>     type: String // Explicación de la respuesta correcta 
>   }
> });
> 
> const Question = mongoose.model('Question', QuestionSchema);
> 
> module.exports = Question;
> ```

@crimanlor conoce una forma de obtener un documento aleatorio de una colección de MongoDB usando un "aggregate". Quizás podríais utilizarlo para vuestro _endpoint_

**Comment by SharmarAndrey** [comment]
```
 He encontrado algunos errores en nuestra `Eschema:`

1. Hay que cambiar en modelo `require` por `required,` para  todos los campos;
2.  Linea 39 return: `Array.length(-4)` no va a funcionar, porque return no es un campo valido de mogoose. Hay que implementar validacion. Creo que Oscar ha esplicado este en un clase(que podemos anadir validacion a eschema)
3. Para trabajar mas comodo hay que anadir a `pakage.json,` dentro del campo `scripts` esta linea:  "dev": "nodemon app.js", pero antes istalar "nodemon";
4. hay que importar con "require" nuestra Eschema de mongoose, a app.js;
5. Hay que anadir  midelware "app.use(express.json());", para trabajar con JSON;
6. Por que sale "exports.postQuestion" en app.js?   Supongo que es un error y hay que poner "const postQuestion" ?
7. No emos  definido la ruta para hacer POST (app.post('/api/v1/questions', postQuestion);  
8. Hay que preguntar si metemos doto codigo a app.js o creamos carpetas para rutas, controllers e.t.c.
9.  nosotrros tenemos en modelo "const Question = model('question', questionSchema);" Y pasamos dentro de modelo eschema con minuskula, pero requerdo que he preguntado Oscar, en un clase y el ha dicho que hay aquerdo dentro programadores para defenir Modelos con letra Mauscula, para saber que no es funcion normal(no estoy seguro =)). 
10.  Hay que buscara como funciona "aggregate", que mencionado Oscar o preguntar Lorena (tenemos que utilizar en nuestro GET request   /api/v1/question/random', para recibir pregunta aleatoria de nuestra base de datos)
11. Creo que sera buena idea para implementar tambien una funcion que permite mesclar variantes de respuesta dentro de misma pregunta( para que si esta misma pregunta sale a usuario - respuesta correcta tiene que estar en otra posicion)
12. Como podemos asegurarse si, por ejempo, usuario hace test de 💯  preguntas, no le sale misma pregunta en mismo "session" de 💯  preguntas.(o este dejamos para otro equipo?  👯  )

**Comment by omiras** [comment]
Subscribo la mayoría de las cosas que ha comentado @SharmarAndrey , pero algún apunte:

1. ¿Para que se necesita una ruta POST? Todavía no permitimos crear nuevas preguntas tipo test des de nuestra REST API ni des de la aplicación Web
2. En la misma línea: ¿para que sirve la función postQuestion en vuestra issue? Tan solo es necesario insertar algunas preguntas tipo test para hacer pruebas. Lo podéis hacer des de el cliente MongoDB del Visual Studio con el comando db.questions.insertMany(). De hecho, podéis usar los JSON generados por @Daud1979 y @zulcas para insertar algunas 😀 
3. Seguir un modelo MVC seria interesante des de un principio, sí.
4. El nombre del modelo está bien definido : "question". La colección creada será "questions"
5. Sobre el punto 11) -> Con el aggegate de @crimanlor ya escoge una pregunta aleatoria de la colección "questions". Pero os soy sincero: ¡no tengo ni idea de cómo usarlo a través de Mongoose, jaja! Tendréis que investigar.  Si no, por el momento, las podéis recuperar todas y hacer el Math.random() .
6. Sobre los tests, por el momento creo que es suficiente con un test que pruebe que al hacer un GET a /api/v1/questions/random se recupera una pregunta tipo test con la estructura esperada y ya está. ¡Podéis comprobar muchas cosas en el test!
   1. Que dispone de un campo **answerOptions**
   2. Que dicha propiedad es un array de 4 elementos
   3. Que al menos uno de los elementos tiene marcado como isCorrect a **true** 
7. Por cierto, ¿para que sirve el campo **language** del modelo?

¡Muy bien trabajo exponiendo todos los puntos a discutir de la issue!

**Comment by omiras** [comment]
## Para dar por finalizada esta issue
 
2. El endpoint debe devolver una pregunta tipo test, solo una
3. Es interesante que sigamos el MVC (teneis emotional-shelf para basaros en ello)
4. La respuesta del endpoint para cumplir con los principios REST seria itneresanteque fuera minimamente estructurado . un objeto con el campo "message" y otro con "results"
con la información
4. Podemos dejar para mas adelante el "aggregate" para obtener una pregunta random
5. la conexión a base de datos podemos moverla a una carpeta config/db.js (como hicimos en
emotional-shelf)
6. Borrar los comentarios
7. Si os da tiempo -> hacer un test automático usando JEST para probar el endpoint usando
fetch tal y como hicimos en clase.

**Comment by omiras** [comment]
@SharmarAndrey he estado viendo vuestro código y he observado que tienes el editor configurado un pelín diferente de los compañeros por el tema de las identaciones. Vamos a probar una cosa

Crea un fichero de nombre _.editorconfig_ en la raíz de tu proyecto. Pega esta configuración:

```
# Indica que este es el archivo de configuración principal
root = true

# Configuración general para todos los archivos
[*]
# Usa espacios en lugar de tabulaciones
indent_style = space
# Tamaño de la indentación
indent_size = 2
# Fin de línea estilo UNIX
end_of_line = lf
# Codificación de archivos
charset = utf-8
# Inserta una nueva línea al final del archivo
insert_final_newline = true
# Elimina espacios en blanco al final de cada línea
trim_trailing_whitespace = true

# Configuración específica para archivos JavaScript
[*.js]
# Indentación específica para archivos JavaScript
indent_size = 2
# Código fuente, suele permitir líneas largas
max_line_length = 100

# Configuración específica para archivos JSON
[*.json]
# JSON requiere estrictamente indentación de 2 espacios
indent_size = 2
# No permite espacios en blanco finales
trim_trailing_whitespace = false

# Configuración para archivos Markdown y texto
[*.md, *.txt]
# Permite espacios en blanco al final, útil en Markdown
trim_trailing_whitespace = false

# Configuración para archivos YAML
[*.yml, *.yaml]
indent_size = 2
```

Así todos unificaremos la identación, espacios en blanco, etc.

**Comment by omiras** [comment]
Posible mejora de la arquitectura (no es necesario implementar ahora mismo):

Podríamos mover la obtención de la pregunta aleatoria a una función. Algo así como **getRandomQuestion**. En un paso adicional podríamos mover esta función a una carpeta **services**, tal y como hicimos en _Emotional Shelf_ : https://github.com/omiras/emotional-shelf/blob/solution/services/book.services.js

![Image](https://github.com/user-attachments/assets/66eff81a-554c-4023-ad18-8922431e792f)
