### ISSUE TITLE
Poder indicar el número total de preguntas tipo test qué queremos obtener de la base de datos

### ISSUE THREAD

**Issue by omiras** [IronHack-2024/CodeQuestAPI#13]
##  Análisis

Queremos poder pasar un parámetro _query string_ al endpoint /api/v1/questions/random?amount={numQuestions}
Donde _numQuestions_ es un **number** que irá entre 1 y 30. Si el usuario especifica más de 30 en la _query string_ nosotros le devolvemos solo 30

El endpoint debe devolver un JSON siguiendo la estructura del endpoint existente.
La propiedad **results** debe ser un array de objetos

```
{
  "message": "Random question delivered successfully",
  "results": {
    "codeExamples": [],
    "_id": "67213a010da50ae0541d0706",
    "question": "What is the output of 0.1 + 0.2 in JavaScript?",
    "answerOptions": [
      {
        "_id": "6722617d5aa7b2fb887283a8",
        "answer": "0.3",
        "isCorrect": false
      },
      {
        "_id": "6722617d5aa7b2fb887283a9",
        "answer": "0.30000000000000004",
        "isCorrect": true
      },
      {
        "_id": "6722617d5aa7b2fb887283aa",
        "answer": "0.29999999999999999",
        "isCorrect": false
      },
      {
        "_id": "6722617d5aa7b2fb887283ab",
        "answer": "NaN",
        "isCorrect": false
      }
    ],
    "urlSource": "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number"
  }
}
```

Debéis modificar el controlador **getRandomQuestions** ubicado en **controllers/index.controllers.js** para que ahora devuelve un array con las preguntas indicadas en el parámetro **amount**.

Si no especifican parámetro **amount** devolveremos siempre 10 preguntas tipo test.

Seria interesante ver como funciona el **aggregate** de MongoDB para obtener X documentos de forma aleatoria de la colección **questions**. Investigad como hacer esto con Mongoose:

```
db.collection.aggregate([
    { $sample: { size: 1 } }
])
```

## Criterios de aceptación

- [x] Existe un endpoint en /api/v1/questions/random que al hacer un GET obtenemos 10 preguntas tipo test
- [x] Existe un endpoint en /api/v1/questions/random que permite recibir una _query string_ para indicar el número de respuestas entre 1 y 30 (si es más de 30, siempre devolvemos 30)

### Precondiciones
1. Clona el repositorio `CodeQuestAPI` y asegúrate de estar en la rama `feature/13-questions-amount` ejecutando:
    ```
    git clone -b feature/13-questions-amount <https://github.com/tu-usuario/CodeQuestAPI.git>
    ```
2. Inicializa el proyecto con el comando:
    ```
    npm install
    ```
3. Consulta el archivo `.env.example` en la raíz del proyecto y crea un archivo `.env` siguiendo el mismo formato.
4. En el archivo `.env`, agrega las siguientes variables:
    - `PORT`: el puerto en el cual deseas que se ejecute la aplicación (por ejemplo, `PORT=3000`).
    - `MONGODB_URI`: la URI de conexión a tu base de datos MongoDB. **Puedes solicitárnosla directamente para usar la conexión creada para este proyecto**.
5. Levanta el servidor ejecutando el comando:
    ```
    npm run dev
    ```

### Test Case 1 - Navegar al endpoint `/api/v1/questions/random`
- **Acción:** Abre cualquier navegador de tu elección e ingresa: `http://localhost:3000/api/v1/questions/random`.
- **Resultado esperado:** Debe mostrarse una respuesta de diez preguntas con formato JSON, es decir, en el siguiente formato:

```
[
  {
    "_id": "id_de_la_pregunta",
    "question": "Texto de la pregunta aquí",
    "codeSnippet": "Fragmento de código si es necesario, si no, dejar vacío",
    "answerOptions": [
      {"answer": "Opción 1", "isCorrect": true},
      {"answer": "Opción 2", "isCorrect": false},
      {"answer": "Opción 3", "isCorrect": false},
      {"answer": "Opción 4", "isCorrect": false}
    ],
    "explanation": "Explicación de la respuesta correcta",
    "urlSource": "Fuente de procedencia de la pregunta"
  }
]
```

Cada parte del JSON debe cumplir con las siguientes condiciones:
- **“question”**: debe contener el texto de la pregunta en formato string.
- **“codeSnippet”**: debe contener un fragmento de código en formato string o estar vacío si no es necesario.
- **“answerOptions”**: debe ser un array de 4 objetos; cada objeto debe tener:
    - Un string `answer` que contenga una posible respuesta.
    - Un booleano `isCorrect` que indique si la respuesta es correcta (`true`) o incorrecta (`false`). **Debe haber solo una respuesta correcta**.
- **“explanation”**: debe contener un string con la explicación de la respuesta correcta.
- "**urlSource**": Debe ser una string con la URL de la fuente de procedencia de la pregunta.

### Test Case 2 - Límite de preguntas devueltas inferior a 30
- **Acción:**  Abre cualquier navegador de tu elección e ingresa: `http://localhost:3000/api/v1/questions/random?amount=1`.
- **Resultado esperado:** La respuesta debe contener 1 pregunta en formato JSON, con la misma estructura que hemos especificado en el caso de prueba anterior.

### Test Case 3 - Límite de preguntas devueltas superior a 30
- **Acción:** Abre cualquier navegador de tu elección e ingresa: `http://localhost:3000/api/v1/questions/random?amount=34`.
- **Resultado esperado:** La respuesta debe contener 30 preguntas, con la misma estructura que hemos especificado en el caso de prueba anterior.

**Comment by crimanlor** [comment]
Hola @omiras! hemos añadido el readme a esta issue. Solo quedaría revisar que se puede añadir al repositorio original. Esta tarde también añadiremos el apartado de "Cómo probar mi issue" aquí en el hilo. Gracias!

**Comment by omiras** [comment]
¡Hola! ¡Muy bien!

Tenemos un problemilla. Al acceder /daily-question no aparece la pregunta del día.

Pasos para reproducir el error:

1. Navegar a /daily-question
2. Aparece un error en el navegador y terminal

Seguramente hay que adaptar el código de **app.js** para que siga funcionando como lo hacía antes. 

Podéis solventar el problema en la misma rama [13-questions-amount](https://github.com/IronHack-2024/CodeQuestAPI/tree/feature/13-questions-amount) y volveos a hacer un **pull request** a la rama main
