### ISSUE TITLE
Crear un endpoint y/o servicio para obtener una pregunta tipo test dado un topic con la IA

### ISSUE THREAD

**Issue by omiras** [IronHack-2024/CodeQuestAPI#15]
## Análisis

Queremos crear un endpoint que permita a nuestra API pedir una pregunta tipo test generada por Gemini.
La ruta podría ser /api/v1/question/ia/
Vamos a tener dos parámetros en la _query string_

- **amount**: número de preguntas tipo test a conseguir (entre 1 y 10). Si el usuario pide más de 10, darle solo 10. Si el usuario no especifica el parámetro **amount** le daremos 1 (valorar si aumentarlo)
- **topic**. un string sobre el tema que queremos las preguntas tipo test ("css inheritance, javascript methods"). Límite de carácteres entre 2 y 140.  Si no especifican el parámetro **topic** , obtener las preguntas tipo test sobre "front end and back end programming".

La API debe responder con un JSON siguiente el formato establecido. Donde **results** es un array con todas las preguntas tipo test generadas.

```
		res.status(200).json({
			message: "Random question delivered successfully",
			results: randomQuestion
		});
```

**Opcionalmente si hay tiempo**: Guardar las preguntas generadas por IA en la base de datos. Acordaos que habrá que marcarlas como "Pending" y modificar el modelo 

```
	status: {
		type: String,
		enum: ["approved", "pending"],
		default: "approved"
	}
```

**Comment by nidaakb** [comment]
Junto con @kevmhughes, hemos avanzado en la implementación de los siguientes puntos en el api endpoint:

#### Amount 
Hemos establecido la lógica para controlar el limite entre 1 y 10 de la siguiente manera:
- Si el usuario no define un amount, se le asigna "1" por defecto.
- Limitamos el valor para que esté entre 1 y 10. Si el usuario pide generar más de 10 preguntas, solo obtendrá 10. 
**Control de errores:**
  - Si todo va bien, la respuesta devuelve un `200` con el mensaje "Random question delivered successfully" y un results que contiene un array con la/s pregunta/s generada/s.
  - En caso de error durante la generación, devolverá un `500` con el siguiente mensaje de error: `"Error generating the question"`.

#### Topic
- El parámetro topic define el tema de las preguntas, por ejemplo, `"JavaScript"`. 
- Si el usuario no especifica uno, se usa el tema configurado como predeterminado: `"Frontend and Backend programming".`
- Implementado la siguiente validación para el texto en topic: debe tener un mínimo de 2 caracters y un máximo de 140. 
  - Si no cumple esta condición, devuelve el siguiente mensaje de error: `"Topic must be at least 2 characters and not exceed 140 characters."
`
#### `Status: "pending"`
Implementación del status "pending" para la preguntas generadas por AI. Usamos el spread operator junto con push añadimos el `status: "pending"` a las preguntas generadas por AI. Falta poder añadirlo en el modelo.

#### Capturas y código 

<img width="1789" alt="amount_validation" src="https://github.com/user-attachments/assets/0759d564-88e9-4fb7-94a8-b4c8a7b244a3">
<img width="883" alt="topic_validation" src="https://github.com/user-attachments/assets/a976f754-de18-4b14-8a46-e0db7ff4943e">


```javascript
app.get('/api/question/ai', async (req, res) => {

    const topic = req.query.topic || "frontend and Backend programming";

    if (topic.length < 2 || topic.length > 140) {
    return res.status(400).json({ error: "Topic must be at least 2 characters and not exceed 140 characters."});
    }

    const amount = Math.min(Math.max(parseInt(req.query.amount) || 1, 1), 10);
    const questions = [];

    try {
        for (let i = 0; i < amount; i++) {
            const quizData = await generateMultipleChoiceQuestion(topic);
            questions.push({
                ...quizData, 	
                status: "pending"
	});
        }
        res.status(200).json({
            message: "Random question delivered successfully",
            results: questions
        });
    } catch (error) {
        res.status(500).json({ error: "Error generating the question" });
    }

})

```

**Comment by omiras** [comment]
¡Buen trabajo!

Siguiendo las reflexiones de la conversación privada de Slack:

1. Quizás **generateMultipleChoiceQuestion** podria estar implementado dentro de **services/questions.services.js.** La naturaleza de la carpeta **services** es ubicar en ella cualquier llamada a un servicio externo, des de una consulta a base de datos o en vuestro caso, una llamada a la API de Gemini.
2. Puede que no necesitemos la función dentro de la carpeta **tools**

¡Keep the good work!

**Comment by kevmhughes** [comment]
He creado una nueva rama para trabajar en la funcionalidad un poco más.  Aquí están los cambios que he realizado:

Estructura de Código:
- He movido la lógica a la carpeta services.
- La función auxiliar createPrompt se encuentra ahora en la carpeta utils.

Mejora de la Legibilidad:
- He añadido comentarios al código para facilitar su comprensión y legibilidad.

Puedes revisar los cambios en el siguiente enlace: [feature/15-generate-AI-questions](https://github.com/IronHack-2024/CodeQuestAPI/tree/feature/15-generate-AI-questions).

Podemos comentarlo más a fondo luego si quieres. Me conectaré sobre las 19:30.

**Comment by omiras** [comment]
Podéis incluir test automático de integración. Un ejemplo: https://github.com/IronHack-2024/CodeQuestAPI/blob/main/test/qustion.test.js
