### ISSUE TITLE
Poder proponer preguntas nueva tipo test desde un formulario, por ejemplo, en /submit-new-question

### ISSUE THREAD

**Issue by omiras** [IronHack-2024/CodeQuestAPI#16]
## Análisis

Crear un formulario en /submit-new-question donde poder proponer nuevas preguntas tipo test 
Al acceder al endpoint se renderiza un formulario con los siguientes campos

1. Un caja de texto (textarea) para indicar la pregunta
2. 4 cajas de texto para indicar las posibles respuestas
3. Alguna forma de marcar la respuesta correcta.

Siguiendo todo el diseño propuesto por [Eva](https://www.figma.com/design/0mQuyp0NohGnK1F5E4JUmv/Code-Quest-API?node-id=18-350&t=BbjOOYtsUPmWVeG7-1)

Al hacer "Submit" se debe guardar en la base de datos. Para crear un nuevo documento en la base de datos usamos el Question.create(). Todo lo que sea comunicación con la base de datos tiene que ir en el fichero services/questions.services.js
Debéis especificar que el campos "status" es "Pending". 

Los datos del formulario deberían ser enviados a través del método POST al endpoint /submit-new-question.

## El modelo

Debes modificar el modelo para que tenga en cuenta que la pregunta esta pendiente de validación

```
	status: {
		type: String,
		enum: ["approved", "pending"],
		default: "approved"
	}
```

## Criterios de aceptación

- [x] Al acceder a la vista /submit-new-question se renderiza el formulario esperado
- [x] Se aplican validaciones de formulario 
- [x] Si validan todos los campos se puede hacer clic en el botón de "submit" y enviar los datos a un nuevo endpoint 
- [x] Se inserta un nuevo documento en la colección **questions** con todos los datos de la pregunta tipo test y con el campo "status" a "pending"

**Comment by omiras** [comment]
@evahuertas ¿podrías hacer una pantalla en figma de este formulario?

**Comment by omiras** [comment]
Ejemplo: ![Image](https://github.com/user-attachments/assets/446fe09d-7134-41da-b63e-99acb903cca1)

**Comment by zulcas** [comment]
Posibles cosas a considerar:
- Hay que considerar en el formulario el campo del modelo codeExamples?
-Solo se pueden 4 respuestas?

**Comment by omiras** [comment]
Estaría bien que al insertar correctamente la respuesta en la base de datos mostrara la misma vista, con un fondo negro, con un mensaje informativo diciendo que "Gracias por tu aportación. bla bla bla". "Revisaremos la aportación y la aprobaremos en el menor tiempo posible"

**Comment by zulcas** [comment]
- Hemos conseguido implementar el nuevo endpoint para la pregunta y las 4 respuestas. 
- Hemos añadido validación de lado servidor al formulario para garantizar que al menos 1 respuesta es marcada como correcta.
- Todos los campos de respuesta del formulario y el de pregunta son required
- Si pregunta es añadida correctamente aparece un pop-up de texto indicando que es correcto
-Si ninguna respuesta es marcada como correcta, aparece el mismo pop-up pero con texto indicando error. 
Como bugs encontrados para solucionar:
-Una vez enviado el formulario, se limpian los campos pero si se vuelve a enviar se mantiene la infromación enviada previamente. 
Mejora implementación
-Añadir campo codeexamples

**Comment by omiras** [comment]
test

**Comment by omiras** [comment]
teest

**Comment by omiras** [comment]
test

**Comment by omiras** [comment]
>   -Una vez enviado el formulario, se limpian los campos pero si se vuelve a enviar se mantiene la infromación enviada previamente.

Ok, le echamos un vistazo hoy

>   -Añadir campo codeexamples

Sí, en varias partes de la aplicación estamos ignorando este campo. Tenemos que abordarlo en la reunión de hoy. No estamos abordándolo en

1. Daily Question
2. Generar preguntas para KAhoot!

En esta issue este campo es lo de menos. Quiero decir: si la pregunta tipo test no tiene un ejemplo de código, no pasa nada. Se puede insertar en la base de datos.

**Comment by omiras** [comment]
- la transformación debería hacerse el index.controllers. el service tan solo debería insertar la pregunta

**Comment by dnlslcd** [comment]
## How To Test

### Preconditions:

1. Clone the [submit-new-question](https://github.com/IronHack-2024/CodeQuestAPI/tree/feature/16-submit-new-question) repo.
2. Initialise it with the command: “npm install”.
3. Make sure you're connecting to the right database via the following MongoDB URI: "mongodb+srv://codequestapi:codequestapi@cluster1.vv25n.mongodb.net/codequestapi-submit-question"

### Test Case 1 - Access the form 

**Action:** head over to "http://localhost:3000/submit-new-question".

**Expected result:** a view with a form should be displayed on the browser. It should contain 5 fields in total (a text area to write the question and 4 text fields for the answers) plus 4 checkboxes attached to the answers' fields:

![captura-form-view](https://github.com/user-attachments/assets/cfe8835f-8533-4fad-af19-43d0ec8aac55)










### Test Case 2 - Submit a new programming question 

**Action:** write a sample question and the possible answers, mark the correct one using the checkbox. Click the "Send" button.

![captura-campos-rellenados](https://github.com/user-attachments/assets/9e7577e2-0ef3-4f23-95e6-b29cb5094024)

**Expected result:** a pop-up confirming the submission and thanking you for the contribution should appear. The former data on the form will disappear so new data can be written. You can close the pop-up either with the "Close" button or clicking anywhere outside of it. 

![captura-pop-up](https://github.com/user-attachments/assets/e6f61595-37ea-48ff-81a7-eb5605843057)



### Test Case 3 - Try to submit another question 

**Action:** right after closing the pop-up, repeat the process and hit the button. No need to refresh the page.

**Expected result:** same as Test Case 2.
