### ISSUE TITLE
Hacer uso de los snipets de código o codeExamples en la app

### ISSUE THREAD

**Issue by omiras** [IronHack-2024/CodeQuestAPI#24]
# Análisis

Necesitamos que _codeExamples_ no sea nunca recuperado por /daily-question ni /template-form
Los endpoints dentro de /api **sí** deben devolver codeExamples.

Comprobar si podemos unificar todas las consultas de preguntas **random** a nuestra base de datos en base a un filtro. La idea sería eliminar la función getRandomQuestionWithoutCodeExamples
Modificar la función **getRandomQuestion** y ponerle de nombre **getRandomQuestionsDB** en  **services.questions.js** para que acepte dos parámetros : (amount, filter)

Si no se especifica un _filter_ , debe devolver una muestra aleatória de ${amount} documentos de la base de datos.
Entendemos un _filter_ como un objeto donde filtramos los documentos que queremos obtener de la base de datos. Por ejemplo:

`  const questions = await getRandomQuestionsDB(1, {codeExamples: []});'

Devuelve 1 pregunta aleatoria de la base de datos que tenga el campo codeExamples vacío.

Es importante verificar en todos los sitios del código donde consumimos estas funciones y adaptarlo. Por ejemplo, en "/daily-question" en app.js o en los controladores de nuestra REST API

Tampoco deben recuperarse las preguntas que tienen el status: "pending". Como esto es algo que de momento queremos que **siempre** se cumpla, podemos valorar si incluir esta condición dentro de la función **getRandomQuestionsDB**

## Criterios de aceptación

- [x] Existe una única función de nombre getRandomQuestionsDB
- [x] He adaptado el código en todas las partes de la aplicaicón donde usábamos getRandomQuestions y getRandomQuestionWithoutCodeExamples
- [x] Ningun endpoint o funcionalidad de la app recupera o muestra preguntas con el **status** a "pending"

**Comment by crimanlor** [comment]
Hola! este es el refactor que hemos aplicado para poder añadir los **filtros** para devolver preguntas con **ejemplos de código para getRandomQuestions, pero no para getDailyQuestion** y **no devolver preguntas con status: "pending"**:

## question.services.js
1. Se ha agregado el **parámetro includeCodeExamples** con valor por defecto true al servicio **getRandomQuestionsDB**.
2. El bloque try obtiene preguntas cuyo **status no sea "pending"**.
- Si **includeCodeExamples es false** (cuando se llama desde el **endpoint /daily-questions**), solo se devuelven **preguntas sin ejemplos de código**.
- Si se llama desde el **endpoint de la API**, se devuelven las preguntas según el parámetro amount y **se incluyen los ejemplos de código (si están presentes)**.

![question services](https://github.com/user-attachments/assets/8fa4e031-5c96-4865-bc67-ff6f62126ea9)

## index.controller.js
1. Hemos movido la **lógica del endpoint '/daily-question**', lo hemos nombrado y exportado como **getDailyQuestion**.
2. Dentro de la lógica de getDailyQuestion y el servicio getRandomQuestionsDB, añadimos como parámetro **includeCodesExamples en false** para que nunca se devuelvan preguntas con ejemplos de código al hacer GET de '/daily-question'.

![index controller](https://github.com/user-attachments/assets/e00fdf20-fc89-4c63-bf96-b8a8f81a37f4)

## api.controller.js
Establecemos el valor por **defecto de includeCodeExamples en true** para **getRandomQuestions**.

![api controller](https://github.com/user-attachments/assets/de4f52b5-0099-45e5-a06e-b2acb0378a89)

**Comment by crimanlor** [comment]
Si la lógica está ok, ¿podemos hacer algunos tests esta tarde antes de hacer el merge con main?
