### ISSUE TITLE
Seguridad y límites de uso de la REST API

### ISSUE THREAD

**Issue by omiras** [IronHack-2024/CodeQuestAPI#26]
# Análisis

No queremos que pasen cosas como lo siguiente

1. Intentan cualquier treta para hacer fallar nuestra app Web
2. Nos hagan demasiadas peticiones por segundo a cualquier endpoint y nos tiren la aplicación
3. En general, defendernos de cualquier uso malintencionado (o no) de nuestra app

## Gestión de errores

- Debemos devolver un error 404 "maquetado" cuando intentan acceder a una vista "/" que no existe
- Devolver un 404 cuando hacen una petición a un endpoint de la REST API que no existe (tipo /api/v1/preguntas/random)

- Hay que gestionar correctamente el error 500 inesperado. (ver ejemplos de Tribook y Fototeca)

## Seguridad y límites

- Informarse de para que sirve y cómo funciona el módulo de terceros "helmet". Usarlo en nuestro proyecto
- Para evitar que nos hagan demasiadas peticiones por segundo a cualquiera de nuestros endpoints. **express-limit** permite gestionar estos límites. Investigar un poco sobre el tema y usarlo en nuestros endpoints para protegerlos.  Quizás **helmet** también permite gestionar límites....
- Necesitáis configurar la política CORS para la REST API:
   - Todos los endpoints dentro de "/api" deben permitir GET des de cualquier cliente
   - Todos los endpoints dentro de "/"  DEBEN Seguir con la política CORS

**Comment by omiras** [comment]
~~Finalmente no hemos configurado helmet. El motivo es que no nos permitía cargar el script de tailwind.~~

Finalmente si hemos podido utilizar helmet. Pero debemos estar alerta por si vuelve a interferir con alguna funcionalidad.

**Comment by SharmarAndrey** [comment]
## Improved Structure of app.js
###To enhance readability and code structure, I reorganized the app.js file as follows:

1. Created a separate security.js file in the middleware folder.
2.  Moved the helmet configuration from app.js to security.js.
3. Imported the security configuration in app.js:
 - `const securityMiddleware = require('./middleware/security');`
4. Applied the security configuration in app.js:
- `app.use(securityMiddleware);`

These changes make the code more modular and easier to maintain.

##Handling Issues with Helmet and /docs Route
After making the changes to modularize app.js, I discovered that helmet was preventing the /docs route from working correctly. 
![Image](https://github.com/user-attachments/assets/884b3498-753b-404f-9e05-c115ee24b936)

Upon further investigation, I found that the error was related to the Content Security Policy (CSP), which was blocking access to an external resource like https://codequestapi.onrender.com/api/v1/test-swagger. Our security policy previously allowed only self (the current source), which prevented the Swagger specification from loading from an external domain.
![Image](https://github.com/user-attachments/assets/f9f5600e-34be-4966-a094-8daaeb213a4e)

To solve this issue, I updated the Content Security Policy (CSP) in the helmet configuration, which defines what resources can be loaded from your website. I modified the helmet configuration in security.js by adding:

```
 connectSrc: [
        "'self'",
        "https://codequestapi.onrender.com"  
      ],

```
Adding this adjustment will allow connections to this server for loading Swagger documentation.
![Image](https://github.com/user-attachments/assets/095b11e5-689a-4be8-95df-03567abb645c)
