### ISSUE TITLE
Crear JSON con preguntas iniciales y modificar el script de la IA

### ISSUE THREAD

**Issue by omiras** [IronHack-2024/CodeQuestAPI#27]
# Análisis

Queremos crear un JSON con las preguntas iniciales de nuestra de base de datos usando el script en tools/descargar.js
Queremos usar el script para generar JSON de cualquier temática relacionada con la programación (python, php, javascrip, etc)
Recordamos que la URL de las preguntas en formato Markdown la tenemos aquí: https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/tree/main/angular

Queremos sobretodo las preguntas de Linkedin de estas categorías:  ['rest-api', 'php', 'python', 'nodejs', 'mysql', 'mongodb', 'javascript', 'html', 'git', 'css', 'react', 'angular', 'other']

Insertar todos los JSON en una base de datos de nombre **codequestapi-production** (des de el plugin de Visual Studio)

Los ficheros generados podemos dejarlos en tools/output

## Modificar script de IA

Deseamos modificar el script de la IA para obtener dos funcionalidades nuevas

1. La respuesta correcte siempre debe estar en el último elemento del array answerOptions
2. Modificar la función del script para recibir un parámetro de nombre **amount** en el que podamos indicar el número de preguntas tipo test que queremos generar (con el objetivo de intentar minimizar el consumo de peticiones de Gemini)

**Comment by SharmarAndrey** [comment]
``` Creo que he acabado hacer la  parte 1 la partwe 2(modificar script) . 
Aunque hay una problema con /daily-question si conectamos a /codequestapi-production . Este endpoint no funciona. Y me necesita ajuda para resolver esta cosa.    
con la base de datos /codequestapi-explanation - fuciona

**Comment by omiras** [comment]
El problema es que el script markdown2Json genera las preguntas tipo test con el campo **answersOptions** en plural, cuando en el modelo lo tenemos en singular: "answerOptions". Hay varias opciones:

1. Sobretodo, modificar el script markdow2json para ajustar esto
2. Borrad todos los documentos de la colección "questions"
3. Si no queréis volver a generar todos los JSON, podéis usar el Visual Studio para cambiar el nombre de todas las propiedades. OJO! Cambiad solo los ficheros con extensión .json

![Image](https://github.com/user-attachments/assets/9ad31972-05bc-43ea-ab80-daa567878311)

4. Volver a insertar todos los documentos.

**Comment by SharmarAndrey** [comment]
```` He terminado totalmente con issure #27.
Totas ras rutas estan funcionando. 
Auque hay  **es importante:** la ruta `/daily-question` no tiene el campo `"explanation"`, por eso no va a salir inguna explicasion cuando el usuari pincha a una respuesta . 

Tambien el Base de las peguntas de markDown hay algunas respuestas sin preguntas.  

Ademas he descubrido, que si llamamos a endpoint `/export-questions` sin parametro `?numberQuestions=[number],` el servidor se calle.
Por eso he implementadpo comprobacion la presencia del parámetro `numberQuestions.`
Tambien he emplimentado   `download-error.ejs ` con mensaje  iformativo para el usuario como se puede descargar preguntas aleatorias en formato Exel

**Comment by SharmarAndrey** [comment]
Acabado con issure #27

**I una cosa importante:**  El base de pregutas de MarkDown no tiene campo  ` explanation:`, por eso en la ruta /daily-question no va a aparecer ninguna explicasion de  pregunta cuando usuario  pincha a una respuesta

Ademas encontrado que si usuario va a la ruta `/export-questions`  sin poner `?numberQuestions=[number]`, en este caso el servidor deja funcionar.   
He areglado esta cosa con implemetacion de `download-error.ejs`  para mandar una pantalla informativa a usuari como el puede descargar fichero con preguntas :  ![Image](https://github.com/user-attachments/assets/6b501247-84b0-4496-9871-de4e7b5d0479)
