### ISSUE TITLE
Poder indicar la categoría

### ISSUE THREAD

**Issue by omiras** [IronHack-2024/CodeQuestAPI#28]
# Análisis

Queremos poder clasificar las preguntas tipo test por categorías

Necesitamos modificar el modelo con un nuevo campo **categories** que será un array de strings. Añadir una validación para que solo podamos indicar un elemento del array

## script Markdown2Json

Modificar el script para que acepte un nuevo parámetro y poder indicar la categoría de las preguntas tipo test generadas. El nombre de las categorías puede coincidir con el nombre de la carpeta de donde hemos obtenido las preguntas tipo test en formato _markdown_. Quizás es adecuado que las categorías las tratemos siempre en minúsculas.

## script IA

 Las preguntas generadas por IA deben ahora también adjuntar un campo **categories**. La misma IA debe seleccionar la categoría correcta. Se recomienda que genere el campo categorías como un array de una sola posición y en minúsculas

## Ubicación de todas las categorías posibles

En conjunción la issue #27 , podemos ir guardando en utils/constants.js , en una variable de nombre **QUESTION_CATEGORIES** todos las categorías que maneja nuestra app

## endpoints

Debemos modificar el endpoint /api/v1/questions/random para que acepte un nuevo parámetro queryString de nombre **category**. Por ejemplo si nos hacen una petición:

`GET /api/v1/questions/random?amount=1&category=css `

Debemos devolver una pregunta aleatoria tipo test donde el valor de su campo **cateogries** es ["css"]

## services

Tendremos que modificar getRandomQuestionDB para poder obtener preguntas tipo tests filtradas por categoría. Ver de que manera impacta esto en la issue #24 . Idealmente, deberíamos implementar la issue #24 antes que esta.

**Comment by omiras** [comment]
Hola,

En el modelo tenemos un campo "status" repetido (en algún merge lo habré mezclado sin darme cuenta)

![Image](https://github.com/user-attachments/assets/9407f2ac-9e0f-48a2-8df3-d08bcf14dc6f)

Creo que podemos aprovechar para establecer también, allí donde haga falta, la propiedad "default". Por ejemplo, codeExamples deberíamos asegurarnos que siempre está informado-> default: [] .

Revisar esto para cada campo, si es necesario, o no, añadir un campo _default_. Hay que mirar esto bien, no podemos simplemente meter un "default" a todos los campos del modelo. Por ejemplo, en /daily-question, ¿cómo se usa el campo _explanation_? ¿El markdown2Json como rellena el campo codeExamples? ¿Por qué tendría que tener un campo _default_ el campo X pero no el campo Y?

**Comment by omiras** [comment]
Trabajo futuro: seria intersante modificar el script de la IA para poder generar N preguntas tipo test sin tener que enviar N peticiones a la API de Gemini. Hacerlo solo en una petición.

**Comment by nidaakb** [comment]
# How to Test

## Preconditions

1. Clone the branch `feature/28-Add-Categories-to-questions` from the repository **CodeQuestAPI**.  
2. Run the command: `npm install` to install dependencies.  
3. Create a `.env` file by duplicating the example `.env` and configure the required secrets, such as the database connection string or API keys.  

   To get an API key, refer to the following documentation: [[Google Gemini API doc](https://ai.google.dev/gemini-api)].  

4. Start the application with the command: `npm run dev`.

### Accepted categories for testing
- `rest-api`, `php`, `python`, `nodejs`, `mysql`, `mongodb`, `javascript`, `html`, `git`, `css`, `react`, `angular`, `other`.

---

## Test Case 1: Retrieve a Random Question from `/api/v1/questions/random` and `/api/v1/questions/ai`

**Action:**  
1. Open a browser or use a tool like Postman/Bruno/Thunderclient to send a GET request:  
   `http://localhost:3000/api/v1/questions/random`
   `http://localhost:3000/api/v1/questions/ai`

**Expected result:**  
A JSON response should be displayed with the following structure:  

```json
{
  "categories": ["category-name"],
  "question": "Question text here",
  "codeExamples": "Add a code snippet if needed, if not leave it empty",
  "answerOptions": [
    {"answer": "Option 1", "isCorrect": false},
    {"answer": "Option 2", "isCorrect": false},
    {"answer": "Option 3", "isCorrect": true},
    {"answer": "Option 4", "isCorrect": false}
  ],
  "explanation": "Explanation here",
  "urlSource": "String",
  "status": "approved or pending"
}
```
Validate the following fields:

`categories` → Should contain an array with one valid category.
`question` → Should be a non-empty string representing the test question.
`codeExamples` → Optional field; can be a code snippet or an empty string.
`answerOptions` → Must be an array of four objects:
     - Each object must have:
          - A answer string field with a possible answer.
          - An isCorrect boolean field, where only one answer has isCorrect: true.
`explanation` → Should provide a clear explanation of the correct answer.
`urlSource` → Must be a valid URL or an empty string if not provided.
`status` → Should be either approved or pending.

## Test Case 2: Retrieve a Question Filtered by Category

**Action:**  
1. Open a browser or use Postman/Bruno/Thunderclient to send a GET request:  
   `http://localhost:3000/api/v1/questions/random?category=html`.
   `http://localhost:3000/api/v1/questions/ai`

**Expected result:**  
- The `categories` field contains `["html"]`.  
- The other fields conform to the structure defined in **Test Case 1**.

## Test Case 3: Default Category Behavior

**Action:**  
1. Send a GET request to:  
   `http://localhost:3000/api/v1/questions/random` & `http://localhost:3000/api/v1/questions/ai`without specifying the `category` parameter.

**Expected result:**  
- The `categories` field should default to `["other"]` if no category is specified.

## Test Case 4: Multiple Questions by Category

**Action:**  
Send a GET request with the `amount` parameter to fetch multiple questions:  
`http://localhost:3000/api/v1/questions/random?amount=3&category=javascript`.
`http://localhost:3000/api/v1/questions/ai?amoun=3&topic=javascript`.

**Expected result:**  
- The response should include an array of 3 question objects, each with the category `javascript`.  
- Validate that all returned questions adhere to the structure defined in **Test Case 1**.


# How to Test Category Validation in Markdown to JSON Script

## Preconditions:
1. Verify that you have a valid [RAW Markdown URL](https://raw.githubusercontent.com/Ebazhanov/linkedin-skill-assessments-quizzes/refs/heads/main/json/json-quiz.md) for testing. 

## Test Case 1: Valid Category

**Action:**  
Run the script with a valid category from QUESTIONS_CATEGORIES. `node markdownToJson.js <RAW_MARKDOWN_URL> testFile json`

**Expected result:**  
- The resulting JSON file (output/testFile.json) contains all questions with the field categories set to "javascript".
The JSON structure adheres to the expected format:
```
{
  "categories": "javascript",
  "question": "Question text here",
  "codeExamples": ["Code snippet here"],
  "answersOptions": [
    {"answer": "Option 1", "isCorrect": false},
    {"answer": "Option 2", "isCorrect": false},
    {"answer": "Option 3", "isCorrect": false},
    {"answer": "Option 4", "isCorrect": true}
  ],
  "urlFont": "<RAW_MARKDOWN_URL>"
}
```
## Test Case 2: Invalid Category

**Action:**  
Run the script with an invalid category from QUESTIONS_CATEGORIES. `node markdownToJson.js <RAW_MARKDOWN_URL> testFile invalidCategory`

**Expected result:**  
- The resulting JSON file (output/testFile.json) contains all questions with the field categories set to "other".
