### ISSUE TITLE
Reorganización de la estrctura del proyecto

### ISSUE THREAD

**Issue by omiras** [IronHack-2024/CodeQuestAPI#29]
# Análisis

Prefijar los diferentes endpoints y estructura de carpetas siguiendo el MVC.

## app.js

- Todos los endpoints de la REST API  deben ir prefijados con "/api"
- Todas las vistas que devuelven HTML (ej: /daily-question) no deben tener ningún prefijo

## routes

- Todas las rutas referentes a la REST API deben ir en el fichero **api.routes.js**
- Todas las rutas referentes al resto de la app en **index.routes.js**

## controllers

- Todos los controladres referentes a la REST API deben ir en el fichero **api.controllers.js**
- Todos los controladores referentes al resto de la app en **index.controllers.js**

## config/tools/utils

- Determinar una carpeta única donde almacenar las diferentes utilizades de la app. Ahora mismo existen **tools** y **utils** . Centralizarlo todo en la carpeta **utils**

## Criterios de aceptación

- [ ] Todas las funcionalidades del app siguien funcionando tras la reestructuración

**Comment by omiras** [comment]
Nos falta mover esto 🙄


```
app.get('/daily-question', async (req, res) => {

  // Obtener la pregunta correspondiente al día
  const questions = await getRandomQuestionWithoutCodeExamples();
  const questionsWithShuffledAnswers = questions.map(question => {
    return {
        ...question,
        answerOptions: shuffleArray(question.answerOptions)
    };
});
  // Renderizar la página con la pregunta y las opciones
  res.render('home',  {questionsWithShuffledAnswers} );
})
```

**Comment by crimanlor** [comment]
Lo cambiamos mañana @omiras porque como hemos hecho algunos cambios para la #24, si pusheamos ahora los cambios no entiendo bien por qué se aplican estos cambios aunque estén en diferente rama. No cerramos esta issue hasta que apliquemos el cambio, para que no se olvide.

**Comment by crimanlor** [comment]
Reubicada la petición GET al endpoint '/daily-questions en **index.routes.js** y en **index.controller.js** la lógica de getDailyQuestion ✅ . Subimos los cambios junto con la issue #24.
