### ISSUE TITLE
[bug]: Failed to load API definition

### ISSUE THREAD

**Issue by omiras** [IronHack-2024/CodeQuestAPI#47]
Our Swagger library sohould work either if we are in a localhost or in any server

##  Steps to reproduce

1. Open https://codequestapi.onrender.com/docs

## Expected results

Information about the current endpoints and query parameters of our API should be displayed wherever the app is displayed: localhost, onreder.com or eventually in vercel.app

## Current results

An Error is displayed: "Failed to load API definition"

![image](https://github.com/user-attachments/assets/dd7e3833-1c0d-4fbc-b328-20fc8d48ff5f)

## Possible solution

As we discussed with @SharmarAndrey it should be enough to update the url object property to "/". 

servers: [
      {
        ~~url: "http://localhost:3000/api",~~
      },
      {
        url: "/"
      },
    ],

In case that does not work, gather some information about how to retrieve current server in NodeJS to use it as value for the url property

**Comment by ekbalam11** [comment]
Let me be in charge of this issue along with other responsive design details. I can keep using branch of issue 25 if it's okay.

**Comment by omiras** [comment]
Actually it would be better to have a different branch for each feature. In case you have to still deal with responsive issues you could open a new issue to handle the responsiveness of the web site. I closed all the other issues 👹
