### ISSUE TITLE
Crear un endpoint tipo /daily-question que renderice una vista con "La pregunta de programación del día"

### ISSUE THREAD

**Issue by omiras** [IronHack-2024/CodeQuestAPI#5]
Algo similar a [La palabra del día](https://lapalabradeldia.com/)

Buena ocasión para practicar CSS, HTML con : 

- Bootstrap 5
- Tailwind Daisy UI - [vídeo](https://youtu.be/PctfrkRo8Fg?si=lxLMWRHUS8ZUFgRB&t=133)
- Cualquier otra que os guste
- Hacerlo a pelo con CSS para practicar

Pero tened en cuenta que esta app va a ser una cara visible de nuestro trabajo, mucho más que un _endpoint_ de una REST API. Por lo cual debe quedar presentable. Os recomiendo investigar por Internete diseños de preguntas tipo Trivial, o cuestionarios tipo test, para ver cómo lo maquetan.

De momento no os preocupéis del modelo ni de variables de entorno. Esto lo van a implementar en IronHack-2024/CodeQuestAPI#8 
Podéis pedir a Chat GPT que os cree un array de preguntas tipo test y usar de momento dicho array.

La vista (EJS) podría enviar el array de preguntas al EJS o bien solo un objeto.  También podéis crear una aplicación del lado clietne y usar _fetch_ para obtenerlos la pregunta de /api/v1/questions/random . Si no tenéis claro la diferencia entre estas dos aproximaciones, podéis contactar con @omiras .

**Comment by omiras** [comment]
La  página de equipo está definiendo unos colores concretos para usarlos como colores primarios de la aplicaición.
Si tenéis que usar algún verde (por ejemplo para marcar una respuesta como correcta), usad este #41fd5b;

@dnlslcd ¿has investigado otras aplicaciones Web para ver como presentan las preguntas tipo test?
¿Puedes compartir algunos de los enlaces de aplicaciones que hayas investigado?

**Comment by VanyaMark** [comment]
Ejemplos de tests:
- [Solo Quiz](https://www.soloquiz.com/)
- [Testeando](https://www.testeando.es/)

**Comment by omiras** [comment]
> Ejemplos de tests:
> 
> * [Solo Quiz](https://www.soloquiz.com/)
> * [Testeando](https://www.testeando.es/)

En el último son super pesados con los anuncios 😅

**Comment by omiras** [comment]
Esta estética de Manz.dev también mola, está bastante acorde con el logo del proyecto y con la página de equipo (supongo que la mostrarán hoy) 

![Image](https://github.com/user-attachments/assets/1f428276-61d0-405f-83fc-a054d852d5ea)

**Comment by omiras** [comment]
Haced que el objeto que pasais a la vista tenga esta estructura. De hecho podéis usar este mismo ahora:

```
{
  "question": "What does CSS stand for?",
  "answerOptions": [
    {
      "answer": "Cascading Style Sheets",
      "isCorrect": true
    },
    {
      "answer": "Computer Style System",
      "isCorrect": false
    },
    {
      "answer": "Creative Styling Solution",
      "isCorrect": false
    },
    {
      "answer": "Coded Style Syntax",
      "isCorrect": false
    }
  ]
}
```

**Comment by omiras** [comment]
1. Tendrás que adaptar el EJS porque ahora las propiedades se llaman diferente (tu no tenías una propiedad de nombre answerOptions)
2. Tienes que conseguir cambiar el "alert" de JavaScript por algo más visual cuando escoja el usuario la respuesta. Tipo: poner en verde si ha hacertado, o en rojo
3. Tras elegir respuesta, deberías bloquear los otros botones para que no sigan pulsándolo
4. Todo esto vas a hacer en tu lado cliente de JavaScript
5. El "verde" que vamos a usar como color corporativo es el  #41fd5b, úsalo por ejemplo para marcar la respuesta correcta.
6. Puedes pedir a @evahuertas @kevmhughes el tipo de letra que esta usando en la página de about-us. Puede ser una buena idea que tu uses la misma font-family.

**Comment by omiras** [comment]
¡Hola! 

Si se os hace muy _cumbersome_ esto de pasar variables JavaScript a EJS, tenemos dos alternativas

## Opción A: Usar fetch y no pasar datos a la vista

El EJS no recibe datos del controlador. El mismo hace un _fetch_ a /api/v1/questions/random y obtiene la pregunta tipo test de ahí. En la respuesta del fetch la aplicaicón ya debe conocer cual es la respuesta correcta, con lo cual se puede quedar toda la lógica en el lado del cliente (al hacer click en un botón debemos comprobar si ha clicado la respuesta correcta y dar un mensaje en consecuencia)

## Opción B: Al hacer click en una opción se hace una petición a /daily-question o /check-question

La pregunta tipo test se presentan en un formulario con 4 opciones. Seleccionamos una (radiobutton?). Hacemos clic en "Comprobar respuesta". Se envía un POST a /daily-quesiton o /check-question con la opción seleccionada y se vuelve a renderizar la misma vista indicando si el usuario ha hacertado o no.

## Opción C: Cada opción es en realidad un enlace a /daily-question donde la pasamos una query string

Todas las respuestas son en realidad enlaces <a>Respuesta 1</a>, donde enviamos una query string con la opción seleccionada y el id de la pregunta tipo test: 

`<a href="/daily-question?id=1&answer=a>Respuesta 1</a>`.

El endpoint o controlador recibe la query string y renderiza el mismo EJS pero esta vez indicando si el usuario ha acertado  o no.

**Comment by VanyaMark** [comment]
He creado una rama feature/5-daily-question-VM para probar cosas y he conseguido:
- pasar las variables del backend a través de ejs al script del front 
- añadir clase propia de propio stylesheet, pero no consigo que reescriba el Tailwind background color 
- como no se puede reescribir el background con color propio, he añadido Tailwind background color on click (verde en caso de respuesta correcta, rojo en caso de respuesta incorrecta)
- deshabilitar todos los botones en caso de click

ToDos:
- investigar cómo usar colores propios junto con Tailwind (como mínimo hay que adaptar el background color al verde del proyecto, guardarlo en root variable?)
- añadir la tipografía que usan los compañeros
- Pensar cómo presentar la explicación de la respuesta (en el caso que se decida que haya explicación) 
- - al Click añadir link "Más información" ?
- - al Click añadir un div que muestra la explicación en la misma página ?

**Comment by omiras** [comment]
@VanyaMark para los colores custom de Tailwind, si estáis usando directamente el CDN de Tailwind en el <head> del home.ejs:

```
<!doctype html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script src="https://cdn.tailwindcss.com"></script>
  <script>
    tailwind.config = {
      theme: {
        extend: {
          colors: {
            clifford: '#da373d',
          }
        }
      }
    }
  </script>
</head>
<body>
  <h1 class="text-3xl font-bold underline **text-clifford**">
    Hello world!
  </h1>
</body>
</html>
```

Fijaos como el h1 tiene cla clase **text-clifford**

**Comment by dnlslcd** [comment]
Gracias @omiras , ayer Vanya y yo implementamos el color que nos comentaste, junto a la typo que el equipo de Eva y co. nos confirmaron, usando precisamente este método.
