### ISSUE TITLE
fix/50-responsive-design-adjustments

### ISSUE THREAD

**Issue by ekbalam11** [IronHack-2024/CodeQuestAPI#50]
**There are still some issues in the front related to the responsive design of the app.**

### 1. Swagger's div is not centered in one of the media queries above 1400px

![image](https://github.com/user-attachments/assets/dc36f506-9a40-4cee-8e51-62ace559642e)

### 2. Template-form view has an issue at a certain resolution

![image](https://github.com/user-attachments/assets/7111a26b-7d02-47c2-85bb-4d37bc00e4af)

**Comment by kevmhughes** [comment]
**I have addressed these styling issues and more in the latest pull request.**

**However, the Swagger UI is not perfect in mobile views yet:**

This is what the user sees when visiting the docs page:
<img width="432" alt="Screenshot 2024-12-03 at 18 22 31" src="https://github.com/user-attachments/assets/67a70b87-40f9-4188-9090-b5cbed844a68">


This is what the user sees when clicking on a "Questionendpoint": 
<img width="432" alt="Screenshot 2024-12-03 at 18 22 37" src="https://github.com/user-attachments/assets/c8f911c5-4f53-479a-948a-a675c3cb97d2">


This is what the user sees when clicking on the "Try It Out" button: 
<img width="432" alt="Screenshot 2024-12-03 at 18 22 45" src="https://github.com/user-attachments/assets/5b9caeca-1418-4635-95a4-5a14bd6b0c3c">

**Comment by ekbalam11** [comment]
Thanks @kevmhughes, let me check if I can handle the swagger style for mobile.
